### ISSUE TITLE
Statistics for Integers and Floats

### ISSUE THREAD

**Issue by tummala-hareesh** [open-data-toronto/profiler-open-data-toronto#2]
- [x] mean
- [x] min
- [x] max
- [x] median
- [x] count of distinct values

**Comment by mackeynichols** [comment]
I dont want to spam 😅 but I have same question here as in the strings issue re refactoring :
https://github.com/open-data-toronto/profiler-open-data-toronto/issues/4#issuecomment-1097145728

**Comment by tummala-hareesh** [comment]
@mackeynichols 
Organizing these functions into a Class will definitely help. Additionally, it will help us write some unittest as examples. Let me try completing these before our meeting.

**Comment by tummala-hareesh** [comment]
There is room for improvement by writing more unittest cases using data source from ckan. Let's plan that this week.

**Comment by mackeynichols** [comment]
We should add to these analyses:
- [ ] all unique values flag (to help find primary keys)
- [ ] (maybe, if it's not too complex,) some basic outlier analysis

**Comment by mackeynichols** [comment]
for reference:
2ac840cd52e6e333cbd5d24a3002faf4a18ddf41
