### ISSUE TITLE
Statistics for Dates and Datetimes

### ISSUE THREAD

**Issue by tummala-hareesh** [open-data-toronto/profiler-open-data-toronto#3]
- [x] earliest date
- [x] latest date
- [x] earliest time
- [x] latest time
- [x] count of distinct values for date
- [x] count of distinct values for date month
- [x] count of distinct values for date year
- [x] count of distinct values for time

**Comment by mackeynichols** [comment]
for reference:
https://github.com/open-data-toronto/profiler-open-data-toronto/commit/78065ca7ee8497fc571eacf2d0a03b20870a3615

**Comment by tummala-hareesh** [comment]
@mackeynichols 
I don't think above datetime statistics add any value. I think, all the **count of distinct values** stats should be grouped and displayed as below: 

- [ ] Count (%) by Year
- [ ] Count (%) by Month 
- [ ] Count (%) by DOW (day of the week)
- [ ] Count (%) by TOD (hour of the day)

**Comment by mackeynichols** [comment]
Hmmm - so you mean, for example % that of values that were in year 2022 or on a Wednesday or at 2PM, right?

Im open to it :) I wont have time to do it before Friday so feel free to start on it.
Otherwise, Ill make sure I get on it next week :+1:

**Comment by tummala-hareesh** [comment]
% is just an additional metric. I am fine with having just the counts. My point here is the **GROUPING**. 
- [ ] Count by Year - to get this, we simply group all the datetime entries by **year**
- [ ] Count by Month - to get this, we simply group all the datetime entries by **month**
- [ ] Count by DOW - to get this, we simply group all the datetime entries by **dow**
- [ ] Count by TOD - to get this, we simply group all the datetime entries by **tod**

Don't worry. I will handle creation and visualization of these stats. May not be able to do this by tomorrow though. For sure, can be done for next week.

**Comment by mackeynichols** [comment]
For reference:
e88b6a19f2736332e670818883126d041a700252
