### ISSUE TITLE
Statistics for Strings

### ISSUE THREAD

**Issue by tummala-hareesh** [open-data-toronto/profiler-open-data-toronto#4]
- [x] count of distinct values
- [x] count of distinct "words" (string separated by spaces, ignoring things like "this", "that", "a" etc
- [x] min and max string length
- [x] min and max word count per string
- [x] count of distinct "masks" (where every letter of a string is turned into an "L" and every digit turned into a "D")

**Comment by mackeynichols** [comment]
I've added a new `word_count` function to the utils file on the `dev` branch 👍

**Comment by mackeynichols** [comment]
I've added the last statistics we're lookign for into the `word_count` function on the `dev` branch 👍 

@tummala-hareesh IYO should I reorganize these functions into class methods before we go any farther? 
Might make keeping these functions organized easier, for when in the future we have to come back and fix/edit them

**Comment by mackeynichols** [comment]
I am going to:
- [ ] make a python file for string function class(es)
- [ ] put our string functions into a class
- [ ] create working unit tests for that class

**Comment by mackeynichols** [comment]
We should add:
- [ ] all unique flag
- [ ] all numeric values flag

**Comment by mackeynichols** [comment]
For reference:
fcd58fc8768aee83de45958d7d3302ef7a51b592
